# Generated by Django 5.2.4 on 2025-07-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='genre',
            field=models.CharField(default='기타', max_length=32),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='year',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
