# Generated by Django 5.2.4 on 2025-07-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_genre_review_rating_review_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='actor',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='review',
            name='running_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
