# Generated by Django 5.2.4 on 2025-07-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_review_img_alter_review_actor_alter_review_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('SF', 'SF'), ('로맨스', '로맨스'), ('코미디', '코미디'), ('액션', '액션'), ('드라마', '드라마'), ('공포', '공포'), ('기타', '기타')], default='기타', max_length=32),
        ),
    ]
