# Generated by Django 5.2.4 on 2025-07-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtool',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
